<div class="hidden">
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint2.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint2.jpg" alt="GEMA Powder Coat Paint"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint3.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint3.jpg" alt="GEMA Powder Coat Painting"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint4.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint4.jpg" alt="Powder Paint Coating"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint5.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint5.jpg" alt="Powder Coat Paint"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint6.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint6.jpg" alt="Powder Coat Painting"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint7.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint7.jpg" alt="Powder Coating Paint"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint8.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint8.jpg" alt="Powder Paint GEMA"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint9.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint9.jpg" alt="Powder Coat Paint GEMA"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint11.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint11.jpg" alt="GEMA Powder Paint Coating"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint12.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint12.jpg" alt="Powder Coat Paint Metal"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint13.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint13.jpg" alt="Metal Powder Coat"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint14.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint14.jpg" alt="Metal Powder Coat Paint"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint15.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint15.jpg" alt="Metal Powder Coat Painting"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint16.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint16.jpg" alt="Sheet Metal Powder Coat"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint17.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint17.jpg" alt="Sheet Metal Powder Coat Paint"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint18.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint18.jpg" alt="Sheet Metal Powder Coat Painting"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint19.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint19.jpg" alt="GEMA Metal Powder Coat"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint20.jpg" title="GEMA Powder Coat Paint Line"><img class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint20.jpg" alt="GEMA Powder Coat Paint Metal"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth1.jpg" title="GEMA Powder Paint Booth"><img alt="Powder Coat Paint Booth" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth1.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth2.jpg" title="GEMA Powder Paint Booth"><img alt="Powder Paint Booth" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth2.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth3.jpg" title="GEMA Powder Paint Booth"><img alt="Powder Coat Painting Booth" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth3.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth4.jpg" title="GEMA Powder Paint Booth"><img alt="Booth for Powder Coat Painting" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth4.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth5.jpg" title="GEMA Powder Paint Booth"><img alt="Booth for Powder Coat Paint" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth5.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth6.jpg" title="GEMA Powder Paint Booth"><img alt="Powder Coat Paint Metal Booth" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth6.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth7.jpg" title="GEMA Powder Paint Booth"><img alt="Powder Coat Painting Metal Booth" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth7.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth8.jpg" title="GEMA Powder Paint Booth"><img alt="Powder Coat Booth" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth8.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-Booth9.jpg" title="GEMA Powder Paint Booth"><img alt="GEMA Powder Coat Booth" class="lazy" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-Booth9.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg" title="GEMA Powder Paint 5 Stage Wash"><img class="lazy" alt="Powder Coat Wash" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg" title="GEMA Powder Paint 5 Stage Wash"><img class="lazy" alt="Powder Coat Paint Wash" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg" title="GEMA Powder Paint 5 Stage Wash"><img class="lazy" alt="Powder Coat Painting Wash" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg" title="GEMA Powder Paint 5 Stage Wash"><img class="lazy" alt="GEMA Powder Coat Wash" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg"/></a>
	<a class="fancybox" rel="powder" href="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg" title="GEMA Powder Paint 5 Stage Wash"><img class="lazy" alt="GEMA Powder Coat Paint Wash" property="Photograph" src="/_assets/img/galleries/GEMA-PowderPaint-5_Stage_Wash.jpg"/></a>
</div>
