<div class="hidden">
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts.jpg" title="Metal Fabrication"><img alt="Metal Fabrication" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts1.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts2.jpg" title="Metal Assembly"><img alt="Metal Assembly" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts2.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts3.jpg" title="Sheet Metal Fabrication"><img alt="Sheet Metal Fabrication" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts3.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts4.jpg" title="Sheet Metal Assembly"><img alt="Sheet Metal Assembly" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts4.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts5.jpg" title="Metal Fabrication Assembly"><img alt="Metal Fabrication Assembly" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts5.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts6.jpg" title="Metal Assembly Fabrication"><img alt="Metal Assembly Fabrication" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts6.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts7.jpg" title="Steel Fabrication"><img alt="Steel Fabrication" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts7.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts8.jpg" title="Steel Assembly"><img alt="Steel Assembly" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts8.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts9.jpg" title="Stainless Steel Fabrication"><img alt="Stainless Steel Fabrication" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts9.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts10.jpg" title="Stainless Steel Assembly"><img alt="Stainless Steel Assembly" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts10.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts11.jpg" title="Precision Metal Fabrication"><img alt="Precision Metal Fabrication" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts11.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Precision-MiscParts12.jpg" title="Precision Metal Assembly"><img alt="Precision Metal Assembly" class="lazy" property="Photograph" src="/_assets/img/galleries/Precision-MiscParts12.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Misc-Photos.jpg" title="Precision Sheet Metal Fabrication"><img alt="Precision Sheet Metal Fabrication" class="lazy" property="Photograph" src="/_assets/img/galleries/Misc-Photos.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Misc-Photos2.jpg" title="Precision Sheet Metal Assembly"><img alt="Precision Sheet Metal Assembly" class="lazy" property="Photograph" src="/_assets/img/galleries/Misc-Photos2.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Misc-Photos3.jpg" title="Metal Fabrication Provider"><img alt="Metal Fabrication Provider" class="lazy" property="Photograph" src="/_assets/img/galleries/Misc-Photos3.jpg"/></a>
	<a class="fancybox" rel="assembly" href="/_assets/img/galleries/Misc-Photos4.jpg" title="Metal Assemblies Provider"><img alt="Metal Assemblies Provider" class="lazy" property="Photograph" src="/_assets/img/galleries/Misc-Photos4.jpg"/></a>
</div>