<div class="hidden">
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser1.jpg" title="TRUMPF TRULASER"><img alt="Trumpf TruLaser 3030 Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser1.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser2.jpg" title="TRUMPF TRULASER"><img alt="Trumpf TruLaser 3030 Laser" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser2.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser3.jpg" title="TRUMPF TRULASER"><img alt="Trumpf TruLaser Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser3.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser4.jpg" title="TRUMPF TRULASER"><img alt="Trumpf TruLaser Laser" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser4.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser5.jpg" title="TRUMPF TRULASER"><img alt="TruLaser 3030 Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser5.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser6.jpg" title="TRUMPF TRULASER"><img alt="TruLaser 3030 Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser6.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser7.jpg" title="TRUMPF TRULASER"><img alt="TruLaser Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser7.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser8.jpg" title="TRUMPF TRULASER"><img alt="Trumpf TruLaser" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser8.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser9.jpg" title="TRUMPF TRULASER"><img alt="Trumpf Metal Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser9.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser10.jpg" title="TRUMPF TRULASER"><img alt="Sheet Metal Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser10.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser11.jpg" title="TRUMPF TRULASER"><img alt="Trumpf Sheet Metal Laser Cutting" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser11.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser12.jpg" title="TRUMPF TRULASER"><img alt="Trumpf TruLaser 3030" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser12.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser13.jpg" title="TRUMPF TRULASER"><img alt="Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser13.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser14.jpg" title="TRUMPF TRULASER"><img alt="Trumpf TruLaser 3030 Metal Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser14.jpg"/></a>
	<a class="fancybox" rel="laser-cutting" href="/_assets/img/galleries/Trumpf-TruLaser15.jpg" title="TRUMPF TRULASER"><img alt="Trumpf Laser Cutting Machine" class="lazy" property="Photograph" src="/_assets/img/galleries/Trumpf-TruLaser15.jpg"/></a>
</div>